config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:create,:new,:show]

  resource :session, only: [:create,:new,:destroy]

  resources :bands

  resources :albums, except: :index

  resources :tracks, except: :index

  resources :notes, except: :index

end

app/models/album.rb
class Album < ActiveRecord::Base


  belongs_to :band, dependent: :destroy
  has_many :tracks

end

app/models/band.rb
class Band < ActiveRecord::Base


  has_many :albums

end

app/models/note.rb
class Note < ActiveRecord::Base


  belongs_to :track, dependent: :destroy
  belongs_to :user, dependent: :destroy
end

app/models/track.rb
class Track < ActiveRecord::Base


  belongs_to :album, dependent: :destroy
  has_many :notes
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :session_token, presence: true

  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end


  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    if user.is_password?(password)
      return user
    else
      return nil
    end

  end

  has_many :notes



  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    before_action :user_must_be_signed_in


    def new
      @album = Album.new
      @bands = Band.all
      render :new
    end

    def create
      @album = Album.new(album_params)
      @band = @album.band
      if @album.save
        render :show
      else
        render :new
      end
    end

    def destroy
      @album = Album.find(params[:id])
      @album.destroy
      render json: "Album destroyed"
    end

    def show
      @album = Album.find(params[:id])
      @band = @album.band
      render :show
    end

    def edit
      @album = Album.find(params[:id])
      @bands = Band.all
      render :edit
    end

    def update
      @album = Album.find(params[:id])
      @album.update(album_params)
      @band = @album.band
      render :show
    end



    private
    def album_params
      params.require(:album).permit(:title, :band_id, :type_of_album)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def sign_in!(user)
    @current_user = user
    session[:session_token] = @current_user.session_token
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def sign_out!(user)
    @current_user.reset_session_token!
    session[:session_token] = nil
  end

  def user_must_be_signed_in
    if current_user.nil?
      redirect_to new_session_url
    end
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_action :user_must_be_signed_in
  
  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      render :show
    else
      render :new
    end
  end

  def index
    @bands = Band.all
    render :index
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    render json: "Band destroyed"
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.find(params[:id])
    @band.update(band_params)
    render :show
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end



  private
  def band_params
    params.require(:band).permit(:name)
  end


end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  validates :comment, presence: true

  before_action :user_must_be_signed_in

  def new
    @note = Note.new
  end


  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.save
    redirect_to track_url(@note.track)
  end




  private
  def note_params
    params.require(:note).permit(:user_id, :track_id, :comment)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end


  def create
    @user = User.find_by_credentials(params[:user][:email],params[:user][:password])
    if @user.nil?
      render json: "Wrong credentials!"
    end
    sign_in!(@user)
    redirect_to bands_url
  end

  def destroy
    sign_out!(current_user)
    redirect_to new_session_url
  end


  # private
  #   def session_params
  #     params.require(:session).permit(:user => {:email, :password})
  #   end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

    before_action :user_must_be_signed_in

    def new
      @track = Track.new
      @albums = Album.all
      render :new
    end

    def create
      @track = Track.new(track_params)
      @album = @track.album
      if @track.save
        render :show
      else
        render :new
      end
    end

    def show
      @track = Track.find(params[:id])
      @album = @track.album
      @note = Note.new
      render :show
    end

    def destroy
      @track = Track.find(params[:id])
      @track.destroy
      render json: "Track destroyed"
    end

    private
    def track_params
      params.require(:track).permit(:title, :album_id, :track_type, :lyrics)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in!(@user)
      render json: "You're in!"
    else
      render :new
    end
  end


  def show
    @user = User.find(params[:id])
    render :show
  end


private

  def user_params
    params.require(:user).permit(:email, :password)
  end




end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/edit.html.erb
<h1>Please Update Album Information!</h1>

<form action="<%=album_url(@album)%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"

  <label for="album_title">Album Title</label>
  <input
    type="text"
    name="album[title]"
    id="album_title"
    value="<%= @album.title %>"
  <br>

  <label for="album_band_id">Band Name</label>
  <select name="album[band_id]" id="band_id">
    <option></option>
    <% @bands.each do |band| %>
      <option
        <%= band.id == @album.band_id ? "selected" : "" %>
        value="<%= band.id %>">
        <%= band.name %>
      </option>
    <% end %>
  </select>
  <br>
  <p>
  </p>

  <label for="album_type_of_album">Album Type</label>
  <br>
  <p>
  </p>
  <input
    type="radio"
    name="album[type_of_album]"
    value="Studio"
    id="album_type_of_album_studio"
    <%= @album.type_of_album == "Studio" ? "checked" : "" %>>
  <label for="album_type_of_album_studio">Studio</label>
  <input
    type="radio"
    name="album[type_of_album]"
    value="Live"
    id="album_type_of_album_live"
    <%= @album.type_of_album == "Live" ? "checked" : "" %>>
  <label for="album_type_of_album_live">Live</label>
  <br>
  <p>
  </p>

  <input type="submit" value="Enter Album Information">

</form>

app/views/albums/new.html.erb
<h1>Please Enter Album Information!</h1>

<form action="/albums" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"

  <label for="album_title">Album Title</label>
  <input
    type="text"
    name="album[title]"
    id="album_title"
    value="<%= @album.title %>"
  <br>

  <label for="album_band_id">Band Name</label>
  <select name="album[band_id]" id="band_id">
    <option></option>
    <% @bands.each do |band| %>
      <option
        <%= band.id == @album.band_id ? "selected" : "" %>
        value="<%= band.id %>">
        <%= band.name %>
      </option>
    <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="album[type_of_album]"
    value="Studio"
    id="album_type_of_album_studio"
    <%= @album.type_of_album == "Studio" ? "checked" : "" %>>
  <label for="album_type_of_album_studio"><Studio></label>
  <input
    type="radio"
    name="album[type_of_album]"
    value="Live"
    id="album_type_of_album_live"
    <%= @album.type_of_album == "Live" ? "checked" : "" %>>
  <label for="album_type_of_album_live"><Live></label>
  <br>

  <input type="submit" value="Enter Album Information">

</form>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<h2><%= "Performed by #{@band.name}" %></h2>
<% if @album.type_of_album == "Studio" %>
  <h2>Performed in Studio</h2>
<% else %>
  <h2>Performed Live</h2>
<% end %>

<h2>Tracks</h2>
<% @album.tracks.each do |track| %>
  <%= link_to track.title, track_url(track) %>
  <br>
<% end %>
<br>


<a href="<%=edit_album_url(@album)%>">Edit Album</a>
<%= link_to @album.band.name, band_url(@album.band) %>
<%= button_to "Delete Album", album_url(@album), method: :delete %>

app/views/bands/edit.html.erb
<h1>Please Update Band Information!</h1>

<form action="<%=band_url(@band)%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"

  <label for="name">Band Name</label>
  <input
    type="text"
    name="band[name]"
    id="band_name"
    value="<%= @band.name %>"
  <br>

  <input type="submit" value="Edit Band">

</form>

app/views/bands/index.html.erb
<h1>All Dem Bands</h1>

<% @bands.each do |band| %>
  <%= link_to band.name, band_url(band)%>
  <br>
  <% end %>

app/views/bands/new.html.erb
<h1>Please Enter Band Information!</h1>

<form action="/bands" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"

  <label for="name">Band Name</label>
  <input
    type="text"
    name="band[name]"
    id="band_name"
    value="<%= @band.name %>"
  <br>

  <input type="submit" value="Create Band">

</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<h2>Albums</h2>
<% @band.albums.each do |album| %>
  <%= link_to album.title, album_url(album) %>
  <br>
<% end %>
<br>
<a href="<%=edit_band_url(@band)%>">Edit Band</a>
<%= button_to "Delete Band", band_url(@band), method: :delete %>
<%= link_to "All dem bands", bands_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<% if !current_user.nil? %>
  <ul>
    <li>logged in as <%= current_user.email %></li>
    <li><%= button_to "Logout", session_url, method: :delete %></li>
  </ul>
  <% end %>
<head>
  <title>TheSoundYouNeed</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<form action="/notes" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"

  <label for="note_comment">Note</label>
  <input
    type="text area"
    name="note[comment]"
    id="note_comment"
  <br>

  <input type="submit" value="Submit this note!">

</form>

app/views/tracks/new.html.erb
<h1>Please Enter Track Information!</h1>

<form action="/tracks" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"

  <label for="track_title">Track Title</label>
  <input
    type="text"
    name="track[title]"
    id="track_title"
    value="<%= @track.title %>"
  <br>

  <label for="track_album_id">Album Title</label>
  <select name="track[album_id]" id="album_id">
    <option></option>
    <% @albums.each do |album| %>
      <option
        <%= album.id == @track.album_id ? "selected" : "" %>
        value="<%= album.id %>">
        <%= album.title %>
      </option>
    <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="album[track_type]"
    value="Official"
    id="album_track_type"
    <%= @track.track_type == "Official" ? "checked" : "" %>>
  <label for="track_track_type">Official</label>
  <input
    type="radio"
    name="album[track_type]"
    value="Official"
    id="album_track_type"
    <%= @track.track_type == "Bonus" ? "checked" : "" %>>
  <label for="track_track_type">Bonus</label>
  <br>

  <label for="track_lyrics">Lyrics</label>
  <input
    type="text area"
    name="track[lyrics]"
    id="track_lyrics"
    value="<%= @track.lyrics %>">
  <br>


  <input type="submit" value="Enter Track Information">

</form>

app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>
<h2><%= "On the Album #{@album.title}" %></h2>

<%= button_to "Delete Track", track_url(@track), method: :delete %>
<%= link_to "Track's Album", album_url(@album)%>

app/views/users/new.html.erb
<h1>Please Sign Up!</h1>

<form action="/users" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"

  <label for="user_email">e-mail</label>
  <input
    type="text"
    name="user[email]"
    id="user_email"
    value="<%= @user.email %>"
  <br>

  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">
  <br>

  <input type="submit" value="Sign Up and get that sound you need!">

</form>

app/views/users/show.html.erb
<h1><%=@user.email%></h1>